Ext.define('hhb.view.editprofil', {
    extend: 'Ext.form.Panel',
    alias: 'widget.editprofil',

    requires: [
        'hhb.view.editprofilViewModel',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'editprofil'
    },
    itemId: 'editprofil',
    bodyPadding: 10,
    fieldDefaults: {
        msgTarget: 'under'
    },

    items: [
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Anmeldename*',
            name: 'nickname',
            allowBlank: false
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Vorname',
            name: 'firstname'
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            fieldLabel: 'Nachname*',
            name: 'lastname',
            allowBlank: false
        },
        {
            xtype: 'radiogroup',
            anchor: '30',
            fieldLabel: 'Geschlecht*',
            allowBlank: false,
            items: [
                {
                    xtype: 'radiofield',
                    name: 'sex',
                    boxLabel: 'm&auml;nnlich',
                    inputValue: 'm'
                },
                {
                    xtype: 'radiofield',
                    name: 'sex',
                    boxLabel: 'weiblich',
                    inputValue: 'w'
                }
            ]
        },
        {
            xtype: 'container',
            layout: 'table',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'pr_day',
                    margin: 0,
                    width: 190,
                    fieldLabel: 'Geburtstag*',
                    name: 'day',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    editable: false,
                    forceSelection: true,
                    store: [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31
                    ]
                },
                {
                    xtype: 'combobox',
                    itemId: 'pr_month',
                    margin: '0 0 0 10',
                    width: 90,
                    hideLabel: true,
                    name: 'month',
                    allowBlank: false,
                    editable: false,
                    forceSelection: true,
                    store: [
                        'Januar',
                        'Februar',
                        'März',
                        'April',
                        'Mai',
                        'Juni',
                        'Juli',
                        'August',
                        'September',
                        'Oktober',
                        'November',
                        'Dezember'
                    ]
                },
                {
                    xtype: 'combobox',
                    itemId: 'pr_year',
                    margin: '0 0 0 10',
                    width: 90,
                    hideLabel: true,
                    name: 'year',
                    allowBlank: false,
                    editable: false,
                    forceSelection: true,
                    store: [
                        1900,
                        1901,
                        1902,
                        1903,
                        1904,
                        1905,
                        1906,
                        1907,
                        1908,
                        1909,
                        1910,
                        1911,
                        1912,
                        1913,
                        1914,
                        1915,
                        1916,
                        1917,
                        1918,
                        1919,
                        1920,
                        1921,
                        1922,
                        1923,
                        1924,
                        1925,
                        1926,
                        1927,
                        1928,
                        1929,
                        1930,
                        1931,
                        1932,
                        1933,
                        1934,
                        1935,
                        1936,
                        1937,
                        1938,
                        1939,
                        1940,
                        1941,
                        1942,
                        1943,
                        1944,
                        1945,
                        1946,
                        1947,
                        1948,
                        1949,
                        1950,
                        1951,
                        1952,
                        1953,
                        1954,
                        1955,
                        1956,
                        1957,
                        1958,
                        1959,
                        1960,
                        1961,
                        1962,
                        1963,
                        1964,
                        1965,
                        1966,
                        1967,
                        1968,
                        1969,
                        1970,
                        1971,
                        1972,
                        1973,
                        1974,
                        1975,
                        1976,
                        1977,
                        1978,
                        1979,
                        1980,
                        1981,
                        1982,
                        1983,
                        1984,
                        1985,
                        1986,
                        1987,
                        1988,
                        1989,
                        1990,
                        1991,
                        1992,
                        1993,
                        1994,
                        1995,
                        1996,
                        1997,
                        1998,
                        1999,
                        2000,
                        2001,
                        2002,
                        2003,
                        2004,
                        2005,
                        2006,
                        2007,
                        2008,
                        2009,
                        2010,
                        2011,
                        2012,
                        2013,
                        2014,
                        2015
                    ]
                }
            ]
        },
        {
            xtype: 'textfield',
            anchor: '100%',
            margin: '5 0 0 0',
            fieldLabel: 'E-Mail*',
            name: 'email',
            allowBlank: false,
            vtype: 'email'
        },
        {
            xtype: 'toolbar',
            margin: '15 -10 0 -10',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'btn_save',
                    style: {
                        color: 'white'
                    },
                    iconCls: 'fa fa-save',
                    text: 'Speichern'
                },
                {
                    xtype: 'button',
                    itemId: 'btn_cancel',
                    style: {
                        color: 'white'
                    },
                    iconCls: 'fa fa-times',
                    text: 'Abbrechen'
                }
            ]
        }
    ]

});