/*
 * File: app/view/newInOut.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('hhb.view.newInOut', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newInOut',

    requires: [
        'hhb.view.newInOutViewModel',
        'Ext.form.field.Number',
        'Ext.form.field.Date',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'newinout'
    },
    id: 'newInOut',
    itemId: 'newInOut',
    bodyPadding: 10,
    fieldDefaults: {
        msgTarget: 'under'
    },

    items: [
        {
            xtype: 'textfield',
            anchor: '100%',
            itemId: 'inouttypeofuse',
            fieldLabel: 'Bezeichnung/Verwendungszweck*',
            labelWidth: 200,
            name: 'inoutname',
            allowBlank: false,
            emptyText: 'Reisekosten'
        },
        {
            xtype: 'numberfield',
            anchor: '100%',
            itemId: 'inoutprice',
            fieldLabel: 'Betrag in Euro*',
            labelWidth: 200,
            name: 'inoutprice',
            allowBlank: false,
            emptyText: '250,00'
        },
        {
            xtype: 'datefield',
            anchor: '100%',
            itemId: 'inoutdate',
            fieldLabel: 'Ausgabetag*',
            labelWidth: 200,
            name: 'inoutdate',
            allowBlank: false,
            format: 'd.m.Y'
        },
        {
            xtype: 'checkboxfield',
            anchor: '100%',
            fieldLabel: 'Gebucht*',
            labelWidth: 200,
            name: 'booked',
            inputValue: '1'
        },
        {
            xtype: 'toolbar',
            margin: '15 -10 0 -10',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    formBind: true,
                    itemId: 'btn_save',
                    style: {
                        color: 'white'
                    },
                    iconCls: 'fa fa-save',
                    text: 'Speichern'
                },
                {
                    xtype: 'button',
                    itemId: 'btn_cancel',
                    style: {
                        color: 'white'
                    },
                    iconCls: 'fa fa-times',
                    text: 'Abbrechen'
                }
            ]
        }
    ]

});